# Generated by Django 6.0.1 on 2026-05-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_App', '0003_agriculturalresaleproperty_is_deleted_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enquiry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enquiry_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('enquiry_email', models.CharField(blank=True, max_length=20, null=True)),
                ('enquiry_message', models.TextField(blank=True, null=True)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('enquiry_time', models.TimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
            ],
        ),
    ]
