# Generated by Django 5.2.4 on 2026-05-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_App', '0005_pgcolivingproperty_property_description'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enquiry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, default='+91', max_length=10, null=True)),
                ('enquiry_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_consent', models.BooleanField(default=False)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('enquiry_time', models.TimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
            ],
        ),
    ]
