# Generated by Django 6.0.1 on 2026-06-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_App', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=50, unique=True)),
                ('object_id', models.CharField(blank=True, null=True)),
                ('property_title', models.CharField(blank=True, max_length=500, null=True)),
                ('listing_type', models.CharField(default='rent', max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('utm_path', models.CharField(default='/', max_length=500)),
                ('utm_url', models.TextField()),
                ('utm_source', models.CharField(max_length=255)),
                ('utm_medium', models.CharField(max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_enquiries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enquiry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, default='+91', max_length=10, null=True)),
                ('enquiry_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_consent', models.BooleanField(default=False)),
                ('lead_status', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('followup_notes', models.TextField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('enquiry_time', models.TimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utm_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='CRM_Panel.utmlink')),
            ],
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['category', 'utm_source'], name='CRM_Panel_u_categor_1ce1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['listing_type', 'category'], name='CRM_Panel_u_listing_73987c_idx'),
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['content_type', 'object_id'], name='CRM_Panel_u_content_137a63_idx'),
        ),
    ]
