# Generated by Django 6.0.1 on 2026-05-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_enquiry',
            old_name='owner_phone',
            new_name='enquiry_email',
        ),
        migrations.RemoveField(
            model_name='property_enquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property_enquiry',
            name='enquiry_type',
        ),
        migrations.RemoveField(
            model_name='property_enquiry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='property_enquiry',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='property_enquiry',
            name='property_id',
        ),
        migrations.AddField(
            model_name='property_enquiry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='property_enquiry',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_enquiry',
            name='enquiry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_enquiry',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User_Subscription',
        ),
    ]
