# Generated by Django 5.2.4 on 2026-05-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_alter_propertyfaq_options_and_more'),
        ('CRM_Panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('enquiry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enquiry_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('enquiry_message', models.TextField(blank=True, null=True)),
                ('enquiry_type', models.CharField(default='Phone Reveal', max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contacts', models.IntegerField(default=3)),
                ('used_contacts', models.IntegerField(default=0)),
                ('remaining_contacts', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.subscription_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
            ],
        ),
        migrations.DeleteModel(
            name='AutoLeadCapture',
        ),
        migrations.DeleteModel(
            name='BulkLeadUpload',
        ),
        migrations.DeleteModel(
            name='LeadAgeAnalysis',
        ),
        migrations.DeleteModel(
            name='LeadAssignment',
        ),
        migrations.DeleteModel(
            name='LeadBuyRequest',
        ),
        migrations.DeleteModel(
            name='LeadHistory',
        ),
        migrations.DeleteModel(
            name='LeadStatusUpdate',
        ),
        migrations.DeleteModel(
            name='ManualLeadEntry',
        ),
        migrations.DeleteModel(
            name='WalletRecharge',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
