# Generated by Django 6.0.1 on 2026-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyenquiry',
            name='object_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
