# Generated by Django 6.0.1 on 2026-05-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='enquiry_email',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='enquiry_message',
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
    ]
