# Generated by Django 6.0.1 on 2026-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0002_propertyenquiry_utm_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=50, unique=True)),
                ('property_id', models.IntegerField()),
                ('property_title', models.CharField(max_length=500)),
                ('utm_url', models.TextField()),
                ('utm_source', models.CharField(max_length=255)),
                ('utm_medium', models.CharField(max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_enquiries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
