# Generated by Django 5.2.4 on 2026-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0002_property_enquiry_user_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_price', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_device', models.TextField(blank=True, null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('enquiry_status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Site Visit', 'Site Visit'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_subscription',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='user_subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Property_Enquiry',
        ),
        migrations.DeleteModel(
            name='User_Subscription',
        ),
    ]
