# Generated by Django 6.0.1 on 2026-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0003_utmlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmlink',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utmlink',
            name='listing_type',
            field=models.CharField(default='rent', max_length=50),
        ),
        migrations.AddField(
            model_name='utmlink',
            name='utm_path',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['category', 'utm_source'], name='CRM_Panel_u_categor_1ce1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['listing_type', 'category'], name='CRM_Panel_u_listing_73987c_idx'),
        ),
    ]
