# Generated by Django 6.0.1 on 2026-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0004_utmlink_category_utmlink_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='page_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='utm_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='utm_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
