# Generated by Django 6.0.1 on 2026-06-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0005_propertyenquiry_page_url_propertyenquiry_utm_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_content',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_params',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_path',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_source',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='utm_term',
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='utm_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='CRM_Panel.utmlink'),
        ),
    ]
