# Generated by Django 6.0.1 on 2026-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0006_remove_propertyenquiry_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='lead_status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
