# Generated by Django 6.0.1 on 2026-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0007_propertyenquiry_closed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyenquiry',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='followup_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
