# Generated by Django 6.0.1 on 2026-06-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Panel', '0008_rename_user_propertyenquiry_assigned_to_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utmlink',
            name='property_id',
        ),
        migrations.AddField(
            model_name='utmlink',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='utmlink',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utmlink',
            name='property_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='utmlink',
            index=models.Index(fields=['content_type', 'object_id'], name='CRM_Panel_u_content_137a63_idx'),
        ),
    ]
