# Generated by Django 6.0.1 on 2026-05-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
