# Generated by Django 5.2.10 on 2026-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotsaleproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
