# Generated by Django 6.0.1 on 2026-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('facilities_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facilities_date', models.DateField(blank=True, null=True)),
                ('facilities_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
