# Generated by Django 6.0.1 on 2026-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
