# Generated by Django 5.2.4 on 2026-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('rental_residential', 'Rental Residential'), ('commercial_rental', 'Commercial Rental'), ('pg_coliving', 'PG / Coliving'), ('resale_residential', 'Resale Residential'), ('commercial_resale', 'Commercial Resale'), ('industrial_resale', 'Industrial Resale'), ('agricultural_resale', 'Agricultural Resale'), ('plot_sale', 'Plot Sale')], max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
