# Generated by Django 5.2.10 on 2026-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resaleresidentialproperty',
            name='title',
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='property_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='age_of_property',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='bhk',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='brokerage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='brokerage_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='builtup_area',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='carpet_area',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='facing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='floor_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='furnishing_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='has_legal_dispute',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='has_loan',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='has_tax_due',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='has_tenants',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='is_negotiable',
            field=models.CharField(default='yes', max_length=5),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='manual_brokerage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='num_owners',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='owner_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='ownership_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='residential_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='society_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='uploaded_by_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='uploaded_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='water_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='zone',
            field=models.CharField(max_length=50),
        ),
    ]
