# Generated by Django 5.2.4 on 2026-03-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommercialProperty',
            new_name='CommercialResaleProperty',
        ),
    ]
