# Generated by Django 5.2.4 on 2026-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_propertyfaq_delete_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyfaq',
            options={},
        ),
        migrations.RemoveField(
            model_name='propertyfaq',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='propertyfaq',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('plot', 'Plot'), ('pg', 'PG'), ('villa', 'Villa'), ('coworking', 'Coworking'), ('agriculture', 'Agriculture')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyfaq',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
