# Generated by Django 6.0 on 2026-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_remove_resaleresidentialproperty_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialresaleproperty',
            name='title',
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='commercial_id',
            field=models.CharField(blank=True, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='age_of_property',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='brokerage_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='existing_tenants',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='fire_noc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='legal_dispute',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='loan_on_property',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='location_hub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='manual_brokerage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='num_owners',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='owner_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='ownership_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='property_condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='residential_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='tax_due',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='uploaded_by_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='zone_type',
            field=models.CharField(max_length=50),
        ),
    ]
