# Generated by Django 5.2.4 on 2026-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_facilities_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
