# Generated by Django 6.0.1 on 2026-04-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_facilities_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResalePlotProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Plot Area (sq.ft)')),
                ('plot_type', models.CharField(choices=[('open_plot', 'Open Plot'), ('residential_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot')], max_length=50)),
                ('road_facing', models.CharField(choices=[('main', 'Main Road'), ('internal', 'Internal Road'), ('corner', 'Corner Plot')], max_length=50)),
                ('is_corner_plot', models.BooleanField(default=False, verbose_name='Corner Plot?')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('is_fencing_done', models.BooleanField(default=False, verbose_name='Fencing Done?')),
                ('sanctioning_authority', models.CharField(blank=True, help_text='e.g., MHADA, CIDCO', max_length=255, null=True)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expected Price (₹)')),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated', max_digits=10, null=True)),
                ('brokerage_required', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_brokerage', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=50)),
                ('num_owners', models.CharField(choices=[('1', 'Single Owner'), ('2', '2 Owners'), ('3+', '3+ Owners')], max_length=20)),
                ('has_loan', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_legal_dispute', models.BooleanField(default=False)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('government_tax_paid', models.BooleanField(default=True, help_text='True if Paid, False if Pending')),
                ('pending_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('encumbrance_certificate', models.FileField(blank=True, null=True, upload_to='plot_certificates/')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='plot_videos/')),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
                ('complete_address', models.TextField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('residential_status', models.CharField(choices=[('resident', 'Resident'), ('nri', 'NRI')], default='resident', max_length=20)),
                ('uploader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('uploader_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resale Plot Property',
                'verbose_name_plural': 'Resale Plot Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResalePlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.resaleplotproperty')),
            ],
        ),
    ]
