# Generated by Django 5.2.10 on 2026-06-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_alter_industrialresaleimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotsaleproperty',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
