# Generated by Django 6.0.1 on 2026-04-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_resaleplotproperty_resaleplotimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleIndustrialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('property_type', models.CharField(choices=[('industrial_land', 'Industrial Land'), ('factory', 'Factory'), ('warehouse', 'Warehouse'), ('industrial_shed', 'Industrial Shed'), ('manufacturing_unit', 'Manufacturing Unit'), ('cold_storage', 'Cold Storage'), ('logistics_park', 'Logistics Park')], max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Land Area (sq.ft / acres)')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
                ('property_address', models.TextField(verbose_name='Complete Property Address')),
                ('has_power_supply', models.BooleanField(default=True)),
                ('kva_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='KVA Capacity')),
                ('water_supply', models.CharField(blank=True, choices=[('corporation', 'Corporation'), ('borewell', 'Borewell'), ('both', 'Both')], max_length=50, null=True)),
                ('crane_facility_ready', models.BooleanField(default=False, verbose_name='Crane/Heavy Machinery Ready?')),
                ('road_connectivity', models.CharField(blank=True, choices=[('highway', 'Near Highway'), ('main', 'Main Road'), ('internal', 'Internal Road')], max_length=50, null=True)),
                ('worker_housing_nearby', models.BooleanField(default=False)),
                ('infrastructure_description', models.TextField(blank=True, null=True, verbose_name='Infrastructure/Property Description')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expected Price (₹)')),
                ('brokerage_required', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_brokerage', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=50)),
                ('sanctioning_authority', models.CharField(blank=True, help_text='e.g., MIDC, GIDC', max_length=255, null=True)),
                ('has_loan', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_tenants', models.BooleanField(default=False)),
                ('tenant_details', models.TextField(blank=True, null=True)),
                ('has_legal_dispute', models.BooleanField(default=False)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('has_tax_due', models.BooleanField(default=False, verbose_name='Government Tax Dues Pending?')),
                ('pending_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_clearance_cert_available', models.BooleanField(default=False)),
                ('facilities', models.JSONField(blank=True, default=list, help_text='List of nearby facilities')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of property amenities')),
                ('has_fire_noc', models.BooleanField(default=False)),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Detailed Description')),
                ('compliance_docs', models.FileField(blank=True, null=True, upload_to='industrial/compliance_docs/')),
                ('floor_plan', models.FileField(blank=True, null=True, upload_to='industrial/floor_plans/')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='industrial/videos/')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('residency_status', models.CharField(choices=[('resident', 'Resident'), ('nri', 'NRI'), ('pio', 'PIO')], default='resident', max_length=50)),
                ('uploader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('uploader_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resale Industrial Property',
                'verbose_name_plural': 'Resale Industrial Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResaleIndustrialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='industrial/property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.resaleindustrialproperty')),
            ],
        ),
    ]
