# Generated by Django 6.0 on 2026-06-13 05:36

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_remove_industrialresaleproperty_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='owner_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
