# Generated by Django 5.2.4 on 2026-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_agriculturalresaleproperty_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
