# Generated by Django 5.2.4 on 2026-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_rentalresidentialproperty_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='banks',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='bus_stop',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='cafeteria',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='conference_room',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='fire_safety',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='metro_station',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='power_backup',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='property_images',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='property_title',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='commercialrentalproperty',
            name='security',
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='amenities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='nearby_facilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='age_of_property',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='brokerage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='construction_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='flooring_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='location_hub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='ownership_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='possession_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='property_condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialrentalproperty',
            name='zone_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
