# Generated by Django 6.0.1 on 2026-04-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_resaleindustrialproperty_resaleindustrialimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleAgriculturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('property_type', models.CharField(choices=[('agriculture_land', 'Agriculture Land'), ('farm_land', 'Farm Land'), ('orchard_land', 'Orchard Land')], max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Land Area (Acres)')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('property_address', models.TextField(verbose_name='Complete Address / Landmarks')),
                ('soil_type', models.CharField(blank=True, choices=[('red', 'Red Soil'), ('black', 'Black Soil'), ('alluvial', 'Alluvial Soil'), ('loamy', 'Loamy Soil')], max_length=50, null=True)),
                ('water_source', models.CharField(blank=True, choices=[('well', 'Well'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('river', 'River'), ('none', 'None')], max_length=50, null=True)),
                ('has_irrigation_facility', models.BooleanField(default=False)),
                ('fertility_status', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True)),
                ('previous_crops', models.CharField(blank=True, help_text='e.g., Rice, Wheat, Sugarcane', max_length=255, null=True)),
                ('detailed_description', models.TextField(verbose_name='Property Description')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expected Price (₹)')),
                ('brokerage_required', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_brokerage', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=50)),
                ('has_loan', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_tenants', models.BooleanField(default=False)),
                ('tenant_details', models.TextField(blank=True, null=True)),
                ('has_legal_dispute', models.BooleanField(default=False)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('has_tax_due', models.BooleanField(default=False, verbose_name='Government Tax Dues Pending?')),
                ('pending_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('encumbrance_cert', models.FileField(help_text='7/12 extract or encumbrance cert', upload_to='agricultural/certificates/')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='agricultural/videos/')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('residency_status', models.CharField(choices=[('resident', 'Resident'), ('nri', 'NRI'), ('pio', 'PIO')], default='resident', max_length=50)),
                ('uploader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploader_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('uploader_role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resale Agricultural Property',
                'verbose_name_plural': 'Resale Agricultural Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResaleAgriculturalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agricultural/property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.resaleagriculturalproperty')),
            ],
        ),
    ]
