# Generated by Django 6.0.1 on 2026-06-15 06:51

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_alter_resaleresidentialproperty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgcolivingproperty',
            old_name='pg_property_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='plotsaleproperty',
            old_name='plot_property_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rentalresidentialproperty',
            old_name='rental_residential_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
