# Generated by Django 6.0 on 2026-07-06 06:30

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_agriculturalplotresaleactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='duplicate_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='property_unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
