# Generated by Django 5.2.4 on 2026-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_commercialrentalproperty_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
