# Generated by Django 6.0.1 on 2026-04-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_rentalresidentialproperty_facilities'),
        ('Admin_App', '0005_resaleagriculturalproperty_resaleagriculturalimage'),
    ]

    operations = [
    ]
