# Generated by Django 5.2.10 on 2026-06-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_alter_plotsaleimage_options_plotsalefaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriculturalresaleimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.CreateModel(
            name='AgriculturalResaleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Admin_App.agriculturalresaleproperty')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
