# Generated by Django 6.0 on 2026-07-10 06:17

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_rentalresidentialproperty_duplicate_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='bhk_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
