# Generated by Django 6.0 on 2026-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_commercialrentalpropertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='attached_bathroom',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='colleges_nearby',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='housekeeping',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='lounge',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='markets_nearby',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='offices_nearby',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='power_backup',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='refrigerator',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='security_24x7',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='study_table',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='transport_nearby',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='wardrobe',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='washing_machine',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='wifi_room',
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='common_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='room_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='best_suited_for',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='furnishing_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='pg_for',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='property_managed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
    ]
