# Generated by Django 6.0 on 2026-06-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_alter_agriculturalresaleimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialRentalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Admin_App.commercialrentalproperty')),
            ],
        ),
    ]
