# Generated by Django 6.0.1 on 2026-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_merge_20260425_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_for', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_base_price', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_offer_price', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_discount', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_max_listings', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_offer_start_date', models.DateField(blank=True, null=True)),
                ('plan_offer_end_date', models.DateField(blank=True, null=True)),
                ('plan_desc', models.TextField(blank=True, null=True)),
                ('plan_upload_date', models.DateField(blank=True, null=True)),
                ('plan_upload_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resaleindustrialimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='resaleplotimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='ResaleAgriculturalImage',
        ),
        migrations.DeleteModel(
            name='ResaleAgriculturalProperty',
        ),
        migrations.DeleteModel(
            name='ResaleIndustrialImage',
        ),
        migrations.DeleteModel(
            name='ResaleIndustrialProperty',
        ),
        migrations.DeleteModel(
            name='ResalePlotImage',
        ),
        migrations.DeleteModel(
            name='ResalePlotProperty',
        ),
    ]
