# Generated by Django 6.0 on 2026-06-18 11:42

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_alter_resaleresidentialproperty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
