# Generated by Django 5.2.10 on 2026-04-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_remove_pgcolivingproperty_ac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotSaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_title', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_area', models.FloatField(blank=True, null=True)),
                ('resale_plot_type', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_road_facing', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_corner', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('plot_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('plot_fencing', models.BooleanField(default=False)),
                ('plot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('brokerage', models.CharField(blank=True, max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_ownership', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_loan', models.BooleanField(default=False)),
                ('plot_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('encumbrance_cert', models.FileField(blank=True, null=True, upload_to='plot_docs/certificates/')),
                ('social_video', models.FileField(blank=True, null=True, upload_to='plot_docs/videos/')),
                ('plot_city', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_locality', models.CharField(blank=True, max_length=150, null=True)),
                ('plot_address', models.TextField(blank=True, null=True)),
                ('plot_owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('plot_owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('plot_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_by_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('uploaded_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotSaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_docs/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.plotsaleproperty')),
            ],
        ),
    ]
