# Generated by Django 6.0.1 on 2026-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_subscription_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_details',
            name='plan_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
