# Generated by Django 5.2.10 on 2026-04-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_plotsaleproperty_plotsaleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialResaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('power_supply', models.BooleanField(default=False)),
                ('kva_capacity', models.IntegerField(blank=True, null=True)),
                ('water_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('crane_heavy_machinery', models.BooleanField(default=False)),
                ('road_connectivity', models.CharField(blank=True, max_length=100, null=True)),
                ('worker_housing_nearby', models.BooleanField(default=False)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('brokerage', models.CharField(blank=True, max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_brokerage', models.CharField(blank=True, max_length=100, null=True)),
                ('sanctioning_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_loan', models.BooleanField(default=False)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('existing_tenants', models.BooleanField(default=False)),
                ('tenant_details', models.TextField(blank=True, null=True)),
                ('legal_dispute', models.BooleanField(default=False)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('tax_due', models.BooleanField(default=False)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_clearance_cert', models.BooleanField(default=False)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('compliance_docs', models.FileField(blank=True, null=True, upload_to='industrial_docs/compliance/')),
                ('social_video', models.FileField(blank=True, null=True, upload_to='industrial_docs/videos/')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=150, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('residency_status', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_by_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('uploaded_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialResaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='industrial_docs/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.industrialresaleproperty')),
            ],
        ),
    ]
