# Generated by Django 6.0 on 2026-06-18 13:47

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_commercialrentalproperty_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
