# Generated by Django 6.0.1 on 2026-06-18 09:39

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_alter_resaleresidentialproperty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(blank=True, max_length=200, null=True)),
                ('package_name', models.CharField(blank=True, max_length=200, null=True)),
                ('package_upload_date', models.DateField(blank=True, null=True)),
                ('package_upload_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
