# Generated by Django 6.0 on 2026-06-19 09:54

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_pgcolivingproperty_property_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturalresaleproperty',
            name='resale_agricultural_desc',
        ),
        migrations.RemoveField(
            model_name='commercialresaleproperty',
            name='sanctioning_authority',
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='nearby_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='listed_by_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='listed_by_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='listed_by_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='listed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='listed_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='property_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialresaleproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
