# Generated by Django 5.2.4 on 2026-04-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_merge_20260425_1133'),
        ('Admin_App', '0008_industrialresaleproperty_industrialresaleimage'),
    ]

    operations = [
    ]
