# Generated by Django 6.0 on 2026-07-14 05:25

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_alter_resaleresidentialproperty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalresidentialproperty',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
