# Generated by Django 6.0 on 2026-06-19 11:27

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0009_remove_agriculturalresaleproperty_resale_agricultural_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commercialrentalproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commercialresaleproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='industrialresaleproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotsaleproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalresidentialproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resaleresidentialproperty',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
