# Generated by Django 5.2.4 on 2026-04-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0009_merge_20260428_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalResaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Agricultural Land Listing', max_length=255, null=True)),
                ('agriculture_property_type', models.CharField(choices=[('agriculture_land', 'Agriculture Land'), ('farm_land', 'Farm Land'), ('orchard_land', 'Orchard Land')], max_length=50)),
                ('area', models.DecimalField(decimal_places=2, help_text='Land Area in Acres', max_digits=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('property_address', models.TextField()),
                ('soil_type', models.CharField(blank=True, choices=[('red', 'Red Soil'), ('black', 'Black Soil'), ('alluvial', 'Alluvial Soil'), ('loamy', 'Loamy Soil')], max_length=50, null=True)),
                ('water_source', models.CharField(blank=True, choices=[('well', 'Well'), ('borewell', 'Borewell'), ('canal', 'Canal'), ('river', 'River'), ('none', 'None')], max_length=50, null=True)),
                ('irrigation_facility', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('fertility_status', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('previous_crops', models.CharField(blank=True, max_length=255, null=True)),
                ('resale_agricultural_desc', models.TextField(verbose_name='Property Description')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brokerage', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('brokerage_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_brokerage', models.CharField(blank=True, max_length=50, null=True)),
                ('ownership_type', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=50)),
                ('agri_loan', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agri_tenants', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('tenant_details', models.TextField(blank=True, null=True)),
                ('agri_dispute', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('agri_tax_due', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('pending_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('encumbrance_cert', models.FileField(upload_to='property/docs/encumbrance/')),
                ('property_video', models.FileField(blank=True, null=True, upload_to='property/videos/')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_contact', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('comm_residency', models.CharField(choices=[('resident', 'Resident'), ('nri', 'NRI'), ('pio', 'PIO')], default='resident', max_length=20)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_by_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resaleindustrialimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='resaleplotimage',
            name='property',
        ),
        migrations.CreateModel(
            name='AgriculturalResaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.agriculturalresaleproperty')),
            ],
        ),
        migrations.DeleteModel(
            name='ResaleAgriculturalImage',
        ),
        migrations.DeleteModel(
            name='ResaleAgriculturalProperty',
        ),
        migrations.DeleteModel(
            name='ResaleIndustrialImage',
        ),
        migrations.DeleteModel(
            name='ResaleIndustrialProperty',
        ),
        migrations.DeleteModel(
            name='ResalePlotImage',
        ),
        migrations.DeleteModel(
            name='ResalePlotProperty',
        ),
    ]
