<<<<<<<< HEAD:Admin_App/migrations/0011_user_details_user_id_and_more.py
# Generated by Django 6.0 on 2026-06-24 07:04
========
# Generated by Django 6.0.1 on 2026-06-19 06:00
>>>>>>>> c0f7b434637edc89bdf2118b9a1c3e52e6442b6c:Admin_App/migrations/0010_user_details_user_id_and_more.py

import Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:Admin_App/migrations/0011_user_details_user_id_and_more.py
        ('Admin_App', '0010_agriculturalresaleproperty_property_no_and_more'),
========
        ('Admin_App', '0009_plan_details_alter_resaleresidentialproperty_id'),
>>>>>>>> c0f7b434637edc89bdf2118b9a1c3e52e6442b6c:Admin_App/migrations/0010_user_details_user_id_and_more.py
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resaleresidentialproperty',
            name='id',
            field=models.CharField(default=Admin_App.models.generate_resale_unique_property_id, editable=False, help_text='Automated unique serial lookup tracking tag', max_length=50, primary_key=True, serialize=False),
        ),
    ]
