# Generated by Django 5.2.4 on 2026-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0010_agriculturalresaleproperty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agriculturalresaleproperty',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='agriculturalresaleproperty',
            name='area',
        ),
        migrations.AddField(
            model_name='agriculturalresaleproperty',
            name='land_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agriculturalresaleproperty',
            name='resale_agricultural_desc',
            field=models.TextField(),
        ),
    ]
