# Generated by Django 5.2.4 on 2026-04-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0011_rename_property_address_agriculturalresaleproperty_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='rentalresidentialproperty',
            name='image9',
        ),
        migrations.CreateModel(
            name='RentalResidentialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residential_rent/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.rentalresidentialproperty')),
            ],
        ),
    ]
