# Generated by Django 5.2.4 on 2026-05-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0012_remove_rentalresidentialproperty_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='brokerage',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='brokerage_percentage',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='manual_brokerage',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='room_facilities',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='room_total_beds',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='uploaded_by_contact',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='uploaded_by_email',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='uploaded_by_name',
        ),
        migrations.RemoveField(
            model_name='pgcolivingproperty',
            name='uploaded_by_role',
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='room_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pgcolivingproperty',
            name='sharing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pgcolivingproperty',
            name='best_suited_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PGPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pg/images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_App.pgcolivingproperty')),
            ],
        ),
    ]
