# Generated by Django 6.0.1 on 2026-05-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_subscription_details_plan_duration'),
        ('Admin_App', '0013_remove_pgcolivingproperty_brokerage_and_more'),
    ]

    operations = [
    ]
