# Generated by Django 6.0.1 on 2026-06-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_App', '0002_alter_resaleresidentialproperty_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_en_title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_en_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_start_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_end_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_message', models.TextField(blank=True, null=True)),
                ('contact_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_time', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_enquiry_date', models.DateField(blank=True, null=True)),
                ('contact_enquiry_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(blank=True, max_length=200, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
                ('faq_date', models.DateField(blank=True, null=True)),
                ('faq_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('wishlist_date', models.DateField(blank=True, null=True)),
                ('wishlist_time', models.TimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.user_details')),
            ],
        ),
    ]
