# Generated by Django 6.0.1 on 2026-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=20)),
                ('contact_en_title', models.CharField(blank=True, max_length=100)),
                ('contact_message', models.TextField(blank=True)),
                ('contact_enquiry_date', models.DateField(blank=True, null=True)),
                ('contact_enquiry_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
