# Generated by Django 6.0.1 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_en_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_end_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_start_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact_enquiry',
            name='contact_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_en_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
