# Generated by Django 6.0.1 on 2026-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0003_wishlistproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(blank=True, max_length=200, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
                ('faq_date', models.DateField(blank=True, null=True)),
                ('faq_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
