# Generated by Django 6.0.1 on 2026-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0005_contact_enquiry_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_end_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_enquiry',
            name='contact_start_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
