# Generated by Django 5.2.4 on 2026-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationseo',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationseo',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='intro_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='key',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='pagetype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='schema_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationseo',
            name='secondary_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
